"""empty message

Revision ID: 15a8d0f6f672
Revises: 
Create Date: 2023-05-20 15:27:17.468512

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '15a8d0f6f672'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    op.drop_table('card')
    op.drop_table('post')
    op.drop_table('user_crypto')
    op.drop_table('offer')
    op.drop_table('transaction')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reputation', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('image', sa.String(length=100), nullable=True))
        batch_op.drop_column('coins')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coins', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('image')
        batch_op.drop_column('reputation')

    op.create_table('transaction',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('author', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('card', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author'], ['user.id'], name='transaction_ibfk_1'),
    sa.ForeignKeyConstraint(['card'], ['card.id'], name='transaction_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('offer',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('author', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('coins', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('card', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('transaction', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author'], ['user.id'], name='offer_ibfk_1'),
    sa.ForeignKeyConstraint(['card'], ['card.id'], name='offer_ibfk_2'),
    sa.ForeignKeyConstraint(['transaction'], ['transaction.id'], name='offer_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user_crypto',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('card_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], name='user_crypto_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_crypto_ibfk_1'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('post',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('author', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('subject', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('content', mysql.VARCHAR(length=200), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['user.id'], name='post_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('card',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('image', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('type', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('ability', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('attack', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('health', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rarity', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('comment',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('author', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('subject', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('content', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('thread', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author'], ['user.id'], name='comment_ibfk_1'),
    sa.ForeignKeyConstraint(['thread'], ['post.id'], name='comment_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
